### ISSUE TITLE
License

### ISSUE THREAD

**Issue by leginee** [java-port/clank#3]
Hello,

which License does the code have?
Or can it be released under the APL2?

If so I would try to integrate it back to Netbeans CND modul.
Help is welcome.

All the Best
Peter

**Comment by java-port** [comment]
Hi Peter,
You can open any Java file and see license
https://github.com/java-port/clank/blob/master/modules/org.clang.analysis/src/org/clang/analysis/analyses/AnalysisClangGlobals.java
 It is the same license as was used by LLVM project at the time of conversion.

Hope it helps,
Vladimir

**Comment by leginee** [comment]
Hmm i see. I checked some Java files and did not find the license. 
Thanks for clarifying this.  

All the Best.
